Last Updated: 2/1/2021

UCSD Class Project: Cogs 188

# Supervised Comparison

Description: Below is a comparison of different Supervised Learning Models on a single data set. First one made entirely by myself and the others are imported from sklearn. Due to the binary classification yet multifeature dataset, I thought it would be interesting to explore the different results given different methodologies.

## Breast Cancer Prediction

Breast cancer is one of the most common cancers among women worldwide, representing the majority of new cancer cases and cancer-related deaths according to global statistics, making it a significant public health problem in today’s society.

The early diagnosis of Breast Cancer can improve the prognosis and chance of survival significantly, as it can promote timely clinical treatment to patients. Further accurate classification of benign tumors can prevent patients undergoing unnecessary treatments. Thus, the correct diagnosis of BC and classification of patients into malignant or benign groups is the subject of much research. Because of its unique advantages in critical features detection from complex Brest Cancer datasets, Machine Learning is widely recognized as the methodology of choice in Breast Cancer pattern classification and forecast modelling.

Link to data set: http://archive.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+%28diagnostic%29

Link to sklearn documentation: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html

## Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn.datasets
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tqdm import tqdm

## Load the breast cancer data

In [2]:
# Load Data Set
breast_cancer = sklearn.datasets.load_breast_cancer()

# Turn Data into Dataframe
data = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)
data['class'] = breast_cancer.target

# Seperate the Data
X = data.drop('class', axis = 1)
Y = data['class']

## Some Visualizations of the Data

In [3]:
data.head(5)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [4]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [5]:
#sns.pairplot(data,hue = 'class', palette= 'coolwarm', vars = ['radius_mean', 'texture_mean', 'perimeter_mean','area_mean','smoothness_mean'])

## Split Training and Testing Data

In [6]:
#Encoding categorical data values
from sklearn.preprocessing import LabelEncoder

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [7]:
# Data Splitting

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, stratify= Y, random_state = 42)

In [8]:
# Valu Extraction

X_train = X_train.values
X_test = X_test.values

In [9]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Dictionary to keep all results in
results = {}

## Method 1: Perceptron Class Built

In [11]:
class Perceptron:
    def __init__ (self):
        self.w = None
        self.b = None
    
    def model(self, x):
        # returns the prediction for a single example x
        pred = 0
        decision = np.dot(self.w, x)
        
        if decision >= self.b:
            pred = 1
            
        return pred 
  
    def predict(self, X): 
        # returns the predictions for multiple examples X
        Y = []
        for x in X:
            res = self.model(x)
            Y.append(res)
        return np.array(Y)
    
    def fit(self, X, Y, epochs = 500, learning_rate = .01):
        accuracy = {}
        wt_matrix = []
        max_accuracy = 0
        self.w = np.ones(X.shape[1])
        self.b = 0
        
        for i in tqdm(range(epochs)):
            for x, y in zip(X, Y):
                y_pred = self.model(x)
                
                # Learning
                if y == 1 and y_pred == 0:
                    self.w = self.w + learning_rate * x 
                    self.b = self.b - learning_rate * 1 
                elif y == 0 and y_pred == 1:
                    self.w = self.w - learning_rate * x 
                    self.b = self.b + learning_rate * 1 
          
                wt_matrix.append(self.w)    
            
                accuracy[i] = accuracy_score(self.predict(X), Y)
        
            if (accuracy[i] > max_accuracy):
                max_accuracy = accuracy[i]
                chkptw = self.w
                chkptb = self.b
        
        self.w = chkptw 
        self.b = chkptb 
        print(max_accuracy)

## Initialize and train Perceptron (Method 1)

In [12]:
# Initialize Perceptrion
perceptron = Perceptron()

# Learning
perceptron.fit(X_train, Y_train, 1000, 0.1)

# Predict X_test Results
Y_pred_test = perceptron.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['Perceptron_M1'] = [acc,cm]

100%|██████████| 1000/1000 [08:41<00:00,  1.92it/s]

0.998046875
0.9122807017543859


## Method 2: SKLearn's Perceptron Import 

In [13]:
from sklearn.linear_model import Perceptron

# Train Perceptron
p = Perceptron(random_state = 42) # default epoch=1000, # default learning rate .1
p.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = p.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['Perceptron_M2'] = [acc,cm]

0.9122807017543859


## Method 3: SKLearn's Logistic Regression 

In [14]:
from sklearn.linear_model import LogisticRegression

# Train Logistic Regression Model
log = LogisticRegression(random_state = 42) 
log.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = log.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['LogRegression'] = [acc,cm]

0.9649122807017544


## Method 4: SKLearn's K Nearest Neighbors 

In [15]:
from sklearn.neighbors import KNeighborsClassifier

# Train K Nearest Neighbor Model
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = knn.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['KNN'] = [acc,cm]

0.9824561403508771


## Method 5: SKLearn's Support Vector Machine

In [16]:
from sklearn.svm import SVC

# Train K Nearest Neighbor Model
svm = SVC(kernel = 'linear', random_state = 42)
svm.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = svm.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['SVM'] = [acc,cm]

0.9473684210526315


## Method 6: Kernel SVM

In [17]:
from sklearn.svm import SVC

# Train K Nearest Neighbor Model
svm_k = SVC(kernel = 'rbf', random_state = 42)
svm_k.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = svm_k.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['Kernel_SVM'] = [acc,cm]

0.9649122807017544


## Method 7: SKLearn's Naive Bayes 

In [18]:
from sklearn.naive_bayes import GaussianNB

# Train K Nearest Neighbor Model
gaus = GaussianNB()
gaus.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = gaus.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['NaiveBayes'] = [acc,cm]

0.9473684210526315


## Method 8: SKLearn's Decision Tree 

In [19]:
from sklearn.tree import DecisionTreeClassifier

# Train K Nearest Neighbor Model
dec = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
dec.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = dec.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['DecTree'] = [acc,cm]

0.8771929824561403


## Method 9: SKLearn's Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier

# Train K Nearest Neighbor Model
rm = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
rm.fit(X_train, Y_train)

# Print Accuracy
Y_pred_test = rm.predict(X_test)
acc = accuracy_score(Y_pred_test, Y_test)
print(acc)

# Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_test)

# Add to results
results['RandomForest'] = [acc,cm]

0.9298245614035088


# Results

In [29]:
print(results)

{'Perceptron_M1': [0.9122807017543859, array([[19,  2],
       [ 3, 33]], dtype=int64)], 'Perceptron_M2': [0.9122807017543859, array([[20,  1],
       [ 4, 32]], dtype=int64)], 'LogRegression': [0.9649122807017544, array([[20,  1],
       [ 1, 35]], dtype=int64)], 'KNN': [0.9824561403508771, array([[20,  1],
       [ 0, 36]], dtype=int64)], 'SVM': [0.9473684210526315, array([[20,  1],
       [ 2, 34]], dtype=int64)], 'Kernel_SVM': [0.9649122807017544, array([[20,  1],
       [ 1, 35]], dtype=int64)], 'NaiveBayes': [0.9473684210526315, array([[20,  1],
       [ 2, 34]], dtype=int64)], 'DecTree': [0.8771929824561403, array([[20,  1],
       [ 6, 30]], dtype=int64)], 'RandomForest': [0.9298245614035088, array([[20,  1],
       [ 3, 33]], dtype=int64)]}


In [38]:
for key, val in results.items():
    if len(key) < 4:
        print(key,'\t\tacc:', val[0]*100)
        print(val[1])
        print()
    else:
        print(key,'\tacc:', val[0]*100)
        print(val[1])
        print()

Perceptron_M1 	acc: 91.22807017543859
[[19  2]
 [ 3 33]]

Perceptron_M2 	acc: 91.22807017543859
[[20  1]
 [ 4 32]]

LogRegression 	acc: 96.49122807017544
[[20  1]
 [ 1 35]]

KNN 		acc: 98.24561403508771
[[20  1]
 [ 0 36]]

SVM 		acc: 94.73684210526315
[[20  1]
 [ 2 34]]

Kernel_SVM 	acc: 96.49122807017544
[[20  1]
 [ 1 35]]

NaiveBayes 	acc: 94.73684210526315
[[20  1]
 [ 2 34]]

DecTree 	acc: 87.71929824561403
[[20  1]
 [ 6 30]]

RandomForest 	acc: 92.98245614035088
[[20  1]
 [ 3 33]]



In [39]:
# Done